import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}"
  ],
  theme: {
    extend: {
      colors: {
        primary: "#d0bcff",
        "on-primary": "#3c0090",
        "primary-container": "#7f3dff",
        "on-primary-container": "#f4ecff",
        "on-primary-fixed": "#23005b",
        "on-primary-fixed-variant": "#5700c9",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#d0bcff",
        secondary: "#a6e6ff",
        "on-secondary": "#003543",
        "secondary-container": "#14d1ff",
        "on-secondary-container": "#00566b",
        "secondary-fixed": "#b7eaff",
        "secondary-fixed-dim": "#4cd6ff",
        "on-secondary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#004e60",
        tertiary: "#d3beeb",
        "on-tertiary": "#38294d",
        "tertiary-container": "#76658d",
        "on-tertiary-container": "#f7ebff",
        "tertiary-fixed": "#eddcff",
        "tertiary-fixed-dim": "#d3beeb",
        "on-tertiary-fixed": "#231437",
        "on-tertiary-fixed-variant": "#4f4065",
        background: "#131313",
        "on-background": "#e5e2e1",
        surface: "#131313",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "surface-bright": "#3a3939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "on-surface-variant": "#ccc3d9",
        outline: "#958da2",
        "outline-variant": "#4a4456",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        "inverse-primary": "#7027f0",
        "surface-tint": "#d0bcff",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        display: ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter"],
        "balance-display": ["var(--font-inter)", "Inter"],
        "display-lg-mobile": ["var(--font-inter)", "Inter"],
        "label-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono"],
        "body-lg": ["var(--font-inter)", "Inter"],
        "display-lg": ["var(--font-inter)", "Inter"],
        "body-md": ["var(--font-inter)", "Inter"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "balance-display": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "42px", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", fontWeight: "400" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", fontWeight: "400" },
        ],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "32px",
        gutter: "16px",
        "container-padding-desktop": "40px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "container-padding-mobile": "20px",
        unit: "4px",
      },
    },
  },
  plugins: [],
};

export default config;