import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}"
  ],
  theme: {
    extend: {
      colors: {
        primary: "#022448",
        "on-primary": "#ffffff",
        "primary-container": "#1e3a5f",
        "on-primary-container": "#8aa4cf",
        "on-primary-fixed": "#001c3b",
        "on-primary-fixed-variant": "#2d486d",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#adc8f5",
        secondary: "#006780",
        "on-secondary": "#ffffff",
        "secondary-container": "#5ed8ff",
        "on-secondary-container": "#005c72",
        "secondary-fixed": "#b7eaff",
        "secondary-fixed-dim": "#5bd5fc",
        "on-secondary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#004e61",
        tertiary: "#390061",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#580091",
        "on-tertiary-container": "#c886ff",
        "tertiary-fixed": "#f2daff",
        "tertiary-fixed-dim": "#e0b6ff",
        "on-tertiary-fixed": "#2e004e",
        "on-tertiary-fixed-variant": "#6b00af",
        background: "#f7f9fb",
        "on-background": "#191c1e",
        surface: "#f7f9fb",
        "on-surface": "#191c1e",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#43474e",
        outline: "#74777f",
        "outline-variant": "#c4c6cf",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#adc8f5",
        "surface-tint": "#455f87",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["var(--font-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        display: ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
        "headline-md": ["var(--font-hanken)", "Hanken Grotesk"],
        "balance-display": ["var(--font-hanken)", "Hanken Grotesk"],
        "display-lg-mobile": ["var(--font-hanken)", "Hanken Grotesk"],
        "label-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono"],
        "body-lg": ["var(--font-jakarta)", "Plus Jakarta Sans"],
        "display-lg": ["var(--font-hanken)", "Hanken Grotesk"],
        "body-md": ["var(--font-jakarta)", "Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "balance-display": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" },
        ],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", fontWeight: "400" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": [
          "16px",
          { lineHeight: "24px", fontWeight: "400" },
        ],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "32px",
        gutter: "16px",
        "container-padding-desktop": "40px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "container-padding-mobile": "20px",
        unit: "4px",
      },
    },
  },
  plugins: [],
};

export default config;
